# Generated by Django 4.2.2 on 2023-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(default=0, max_length=35),
        ),
    ]
