# Generated by Django 4.2.2 on 2023-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_hoodie_tshirt_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoodie',
            name='price',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='price',
            field=models.IntegerField(default=25),
        ),
    ]
